export const HEADLINES = [
  "Why Ignoring DATA Will Cost You Time and Sales",
  "Why DATA Is The Only Skill You Really Need",
  "Master (Your) DATA in 5 Minutes A Day",
  "Best DATA Android/iPhone Apps",
  "How To Make Your DATA Look Amazing In 5 Days",
  "Open The Gates For DATA By Using These Simple Tips",
  "How To Use DATA To Desire",
  "DATA Is Essential For Your Success. Read This To Find Out Why",
  "The Quickest & Easiest Way To DATA",
  "This Study Will Perfect Your DATA: Read Or Miss Out",
  "5 Brilliant Ways To Teach Your Audience About DATA",
  "Don't Fall For This DATA Scam",
  "12 Questions Answered About DATA",
  "Quick and Easy Fix For Your DATA",
  "The Philosophy Of DATA",
  "2 Things You Must Know About DATA",
  "Top 25 Quotes On DATA",
  "3 Ways You Can Reinvent DATA Without Looking Like An Amateur",
  "How To Start DATA With Less Than $100",
  "How To Improve At DATA In 60 Minutes",
  "In 10 Minutes, I'll Give You The Truth About DATA",
  "The DATA That Wins Customers",
  "The A - Z Guide Of DATA",
  "Want To Step Up Your DATA? You Need To Read This First",
  "The Secrets To Finding World Class Tools For Your DATA Quickly",
  "Fall In Love With DATA",
  "22 Tips To Start Building A DATA You Always Wanted",
  "Sexy DATA",
  "Answered: Your Most Burning Questions About DATA",
  "Got Stuck? Try These Tips To Streamline Your DATA",
  "9 Ways DATA Can Make You Invincible",
  "Fascinating DATA Tactics That Can Help Your Business Grow",
  "Sick And Tired Of Doing DATA The Old Way? Read This",
  "If You Do Not (Do)DATA Now, You Will Hate Yourself Later",
  "How To Find The Right DATA For Your Specific Product(Service).",
  "The Truth Is You Are Not The Only Person Concerned About DATA",
  "The Ultimate Secret Of DATA",
  "5 Ways Of DATA That Can Drive You Bankrupt - Fast!",
  "DATA: An Incredibly Easy Method That Works For All",
  "The Untold Secret To Mastering DATA In Just 3 Days",
  "Make Your DATAA Reality",
  "Where Is The Best DATA?",
  "Why You Really Need (A) DATA",
  "11 Methods Of DATA Domination",
  "5 Surefire Ways DATA Will Drive Your Business Into The Ground",
  "3 Easy Ways To Make DATA Faster",
  "What Zombies Can Teach You About DATA",
  "Never Changing DATA Will Eventually Destroy You",
  "3 Mistakes In DATA That Make You Look Dumb",
  "A Guide To DATA At Any Age",
  "To People That Want To Start DATA But Are Affraid To Get Started",
  "Turn Your DATA Into A High Performing Machine",
  "10 Things You Have In Common With DATA",
  "Why Most DATA Fail",
  "27 Ways To Improve DATA",
  "Now You Can Have The DATA Of Your Dreams – Cheaper/Faster Than You Ever Imagined",
  "OMG! The Best DATA Ever!",
  "Best Make DATA You Will Read This Year (in 2015)",
  "If DATA Is So Terrible, Why Don't Statistics Show It?",
  "How To Buy (A) DATA On A Tight Budget",
  "15 Lessons About DATA You Need To Learn To Succeed",
  "What Alberto Savoia Can Teach You About DATA",
  "How To Turn DATA Into Success",
  "3 DATA Secrets You Never Knew",
  "3 Tips About DATA You Can't Afford To Miss",
  "Ho To (Do) DATA Without Leaving Your Office(House).",
  "What Everyone Must Know About DATA",
  "Find Out Now, What Should You Do For Fast DATA?",
  "It's All About (The) DATA",
  "How To Turn Your DATA From Zero To Hero",
  "Secrets To Getting DATA To Complete Tasks Quickly And Efficiently",
  "You Can Thank Us Later - 3 Reasons To Stop Thinking About DATA",
  "How To Learn DATA",
  "7 Easy Ways To Make DATA Faster",
  "The Ultimate Guide To DATA",
  "Stop Wasting Time And Start DATA",
  "At Last, The Secret To DATA Is Revealed",
  "Get Rid of DATA Once and For All",
  "Succeed With DATA In 24 Hours",
  "You Will Thank Us - 10 Tips About DATA You Need To Know",
  "DATA? It's Easy If You Do It Smart",
  "Why Everything You Know About DATA Is A Lie",
  "52 Ways To Avoid DATA Burnout",
  "5 Things To Do Immediately About DATA",
  "How To Get (A) Fabulous DATA On A Tight Budget",
  "Marriage And DATA Have More In Common Than You Think",
  "DATA: Do You Really Need It? This Will Help You Decide!",
  "How To Make Your DATA Look Like A Million Bucks",
  "DATA: This Is What Professionals Do",
  "DATA Is Bound To Make An Impact In Your Business",
  "4 Ways You Can Grow Your Creativity Using DATA",
  "Need More Time? Read These Tips To Eliminate DATA",
  "Rules Not To Follow About DATA",
  "10 Tips That Will Make You Influential In DATA",
  "101 Ideas For DATA",
  "How We Improved Our DATA In One Week(Month, Day)",
  "DATA - So Simple Even Your Kids Can Do It",
  "9 Ridiculous Rules About DATA",
  "10 Warning Signs Of Your DATA Demise",
  "How To Save Money with DATA?",
  "Learn To (Do) DATA Like A Professional",
  "5 Brilliant Ways To Use DATA",
  "The Number One Reason You Should (Do) DATA",
  "How To Handle Every DATA Challenge With Ease Using These Tips",
  "The Truth About DATA In 3 Minutes",
  "DATA Strategies For Beginners",
  "The Secrets To DATA",
  "How To Start A Business With DATA",
  "Listen To Your Customers. They Will Tell You All About DATA",
  "Never Lose Your DATA Again",
  "How To Teach DATA Better Than Anyone Else",
  "What Can You Do About DATA Right Now",
  "What Can You Do To Save Your DATA From Destruction By Social Media?",
  "Now You Can Buy An App That is Really Made For DATA",
  "15 Tips For DATA Success",
  "DATA An Incredibly Easy Method That Works For All",
  "10 Ways To Immediately Start Selling DATA",
  "Who Else Wants To Know The Mystery Behind DATA?",
  "The Secret of Successful DATA",
  "The Biggest Lie In DATA",
  "DATA Is Crucial To Your Business. Learn Why!",
  "Read This Controversial Article And Find Out More About DATA",
  "What Is DATA and How Does It Work?",
  "Why DATA Succeeds",
  "Revolutionize Your DATA With These Easy-peasy Tips",
  "Find Out How I Cured My DATA In 2 Days",
  "Use DATA To Make Someone Fall In Love With You",
  "The Ultimate Deal On DATA",
  "The Lazy Way To DATA",
  "5 Secrets: How To Use DATA To Create A Successful Business(Product)",
  "Proof That DATA Is Exactly What You Are Looking For",
  "Why Some People Almost Always Make/Save Money With DATA",
  "Get Better DATA Results By Following 3 Simple Steps",
  "Don't Just Sit There! Start DATA",
  "10 Unforgivable Sins Of DATA",
  "5 Ways You Can Get More DATA While Spending Less",
  "At Last, The Secret To DATA Is Revealed",
  "What You Should Have Asked Your Teachers About DATA",
  "Who Else Wants To Be Successful With DATA",
  "Are You Making These DATA Mistakes?",
  "Are You Embarrassed By Your DATA Skills? Here's What To Do",
  "5 Best Ways To Sell DATA",
  "17 Tricks About DATA You Wish You Knew Before",
  "Why DATA Is No Friend To Small Business",
  "No More Mistakes With DATA",
  "7 Ways To Keep Your DATA Growing Without Burning The Midnight Oil",
  "Want A Thriving Business? Focus On DATA!",
  "Why I Hate DATA",
  "10 Ways To Reinvent Your DATA",
  "DATA Shortcuts - The Easy Way",
  "The Untapped Gold Mine Of DATA That Virtually No One Knows About",
  "Little Known Ways To Rid Yourself Of DATA",
  "Improve(Increase) Your DATA In 3 Days",
  "What Can Instagramm Teach You About DATA",
  "Lies And Damn Lies About DATA",
  "3 Things Everyone Knows About DATA That You Don't",
  "World Class Tools Make DATA Push Button Easy",
  "10 Best Practices For DATA",
  "Interesting Facts I Bet You Never Knew About DATA",
  "Here Is A Quick Cure For DATA",
  "5 Problems Everyone Has With DATA – How To Solved Them",
  "Old School DATA",
  "7 and a Half Very Simple Things You Can Do To Save DATA",
  "Top 10 Tips With DATA",
  "DATA Expert Interview",
  "The Secret of DATA",
  "How DATA Made Me A Better Salesperson",
  "These 5 Simple DATA Tricks Will Pump Up Your Sales Almost Instantly",
  "Never Suffer From DATA Again",
  "Here Is What You Should Do For Your DATA",
  "How To Lose Money With DATA",
  "2 Ways You Can Use DATA To Become Irresistible To Customers",
  "Clear And Unbiased Facts About DATA (Without All the Hype)",
  "Fear? Not If You Use DATA The Right Way!",
  "Learn Exactly How We Made DATA Last Month",
  "What Your Customers Really Think About Your DATA?",
  "The Single Most Important Thing You Need To Know About DATA",
  "5 Ways To Get Through To Your DATA",
  "Can You Really Find DATA (on the Web)?",
  "5 Romantic DATA Ideas",
  "5 Incredibly Useful DATA Tips For Small Businesses",
  "Winning Tactics For DATA",
  "Avoid The Top 10 Mistakes Made By Beginning DATA",
  "10 Secret Things You Didn't Know About DATA",
  "The Lazy Man's Guide To DATA",
  "DATA And Love Have 4 Things In Common",
  "DATA Your Way To Success",
  "Savvy|Smart|Sexy People Do DATA :)",
  "14 Days To A Better DATA",
  "5 Simple Steps To An Effective DATA Strategy",
  "A Surprising Tool To Help You DATA",
  "Don't Be Fooled By DATA",
  "5 Easy Ways You Can Turn DATA Into Success",
  "How To Make More DATA By Doing Less",
  "The Best Way To DATA",
  "I Don't Want To Spend This Much Time On DATA. How About You?",
  "5 Ways DATA Will Help You Get More Business",
  "How To Become Better With DATA In 10 Minutes",
  "Guaranteed No Stress DATA",
  "Top 3 Ways To Buy A Used DATA",
  "Why You Never See DATA That Actually Works",
  "3 Ways To Master DATA Without Breaking A Sweat",
  "Top 10 Tips To Grow Your DATA",
  "Secrets To DATA – Even In This Down Economy",
  "Death, DATA And Taxes",
  "DATA Adventures",
  "Get The Most Out of DATA and Facebook",
  "What Everyone Ought To Know About DATA",
  "How To Teach DATA Like A Pro",
  "How To Sell DATA",
  "How To Earn $398/Day Using DATA",
  "Learn Exactly How I Improved DATA In 2 Days",
  "Should Fixing DATA Take 60 Steps?",
  "DATA: The Samurai Way",
  "How You Can (Do) DATA Almost Instantly",
  "Who Else Wants To Enjoy DATA",
  "Best 50 Tips For DATA",
  "Take The Stress Out Of DATA",
  "The DATA Mystery Revealed",
  "5 Reasons DATA Is A Waste Of Time",
  "Now You Can Have Your DATA Done Safely",
  "Beware The DATA Scam",
  "What Make DATA Don't Want You To Know",
  "Picture Your DATA On Top. Read This And Make It So",
  "DATA Made Simple - Even Your Kids Can Do It",
  "Proof That DATA Really Works",
  "Being A Star In Your Industry Is A Matter Of DATA",
  "Why My DATA Is Better Than Yours",
  "How You Can (Do) DATA In 24 Hours Or Less For Free",
  "How To Win Buyers And Influence Sales with DATA",
  "Congratulations! Your DATA Is (Are) About To Stop Being Relevant",
  "Does DATA Sometimes Make You Feel Stupid?",
  "15 Unheard Ways To Achieve Greater DATA",
  "Find A Quick Way To DATA",
  "DATA And The Chuck Norris Effect",
  "The Ugly Truth About DATA",
  "Your Key To Success: DATA",
  "How To Win Clients And Influence Markets with DATA",
  "Everything You Wanted to Know About DATA and Were Too Embarrassed to Ask",
  "How To Make Your Product Stand Out With DATA",
  "Want More Money? Start DATA",
  "Do DATA Better Than Barack Obama",
  "5 Sexy Ways To Improve Your DATA",
  "You Don't Have To Be A Big Corporation To Start DATA",
  "SuperEasy Ways To Learn Everything About DATA",
  "Everything You Wanted to Know About DATA and Were Afraid To Ask",
  "DATA: What A Mistake!",
  "Little Known Ways to DATA",
];

export const NAMES = [
  "Josephine Wagner",
  "Homer Cervantes",
  "Habiba Mccormick",
  "Hector Simmons",
  "Keyaan Bradley",
  "Lewis Fields",
  "Aron Cochran",
  "Nikita Mcmillan",
  "Emmie Meza",
  "Ameer Leblanc",
  "Zahra Perez",
  "Maximillian Rivas",
  "Marissa Reyes",
  "Ciara Hart",
  "Dillan Morgan",
  "Lily Hobbs",
  "Barney Suarez",
  "Lyra Davis",
  "Charlie Faulkner",
  "Chad Sullivan",
  "Claude Hicks",
  "Asa Hoover",
  "Shane Curry",
  "Pearl Marks",
  "Anoushka Maxwell",
  "Ahmed Matthams",
  "Lyla Bowers",
  "Jana Floyd",
  "Rebecca Butler",
  "Erin Mccall",
  "Sadia Webster",
  "Eden Martinez",
  "Natalie Hunter",
  "Ivan Mercado",
  "Delilah Doherty",
  "Duncan Hartley",
  "Macauley Flynn",
  "Grayson Roberson",
  "Nikhil Pace",
  "Sian Orr",
  "Mikey Thornton",
  "Connor Solis",
  "Kayla Kane",
  "Wayne Sutton",
  "Ellis Aguirre",
  "Kacie Howe",
  "Seren Gallegos",
  "Mathilda Lawson",
  "Earl Aguilar",
  "Tom Ross",
  "Tamsin Barnett",
  "Jerome Hanson",
  "Ruqayyah Brewer",
  "Marilyn Blaese",
  "Oliwia Morse",
  "Ralph Sheppard",
  "Zachary Church",
  "Kaylee Hurst",
  "Mohammad Bruce",
  "Antony Mcpherson",
  "Jane Gamble",
  "Sydney Williams",
  "Ernest Edwards",
  "Safiya Mccullough",
  "Kristina Eaton",
  "Kendra Schwartz",
  "Ali Mcmahon",
  "Siena Lowery",
  "Theodore Hayden",
  "Amanda Mcclain",
  "Leland Gilmore",
  "Hayden Lozano",
  "Emily Wilkinson",
  "Nataniel James",
  "Michael England",
  "Alexander Rich",
  "Carter Hale",
  "Marcus Villarreal",
  "Vincent Olsen",
  "Caleb Trevino",
  "Anais Burton",
  "Karina Owens",
  "Samson Carlson",
  "Edie Crawford",
  "Hugh Little",
  "Daniel Raymond",
  "Bailey Landry",
  "Mikolaj Trujillo",
  "Katrina Davila",
  "Helena Wang",
  "Aoife Fuentes",
  "Juliet Kidd",
  "Marjorie Hahn",
  "Safaa Rose",
  "Valerie Knapp",
  "Dora Obrien",
  "Denzel Norris",
  "Daniela Case",
  "Ricky Short",
  "Cordelia Johns",
];

export const LOREM =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et mauris ligula. Aliquam convallis quam non augue posuere pellentesque. Donec arcu ante, tempor quis libero ac, pharetra venenatis metus. Donec ac rutrum purus, sit amet feugiat purus. Mauris vitae mattis nulla. Nunc auctor suscipit risus, sit amet convallis sem consequat ac. Suspendisse pretium purus a lacus bibendum, et dapibus nunc mattis. Morbi efficitur lectus et justo ornare hendrerit. Nam laoreet venenatis cursus. Nullam massa urna, laoreet ac porttitor eget, pharetra et tellus. Duis cursus tellus sem, ac feugiat erat facilisis nec. Maecenas scelerisque euismod nibh in porttitor. In feugiat felis a molestie maximus. Vestibulum posuere est nisi, ut ultricies ipsum rhoncus nec.\n\nNam neque est, facilisis id rhoncus eu, suscipit vel mauris. Morbi in quam metus. Integer fringilla ultricies volutpat. Fusce non fringilla libero. Donec tristique ac odio sit amet interdum. Donec id justo magna. Quisque dolor felis, porta a justo eget, congue tincidunt libero. Praesent vel leo vel ipsum facilisis eleifend non consequat massa. Nunc leo diam, dignissim nec nunc non, blandit egestas nisi. Ut vitae gravida enim. Sed lorem lacus, tempor vel dignissim vitae, scelerisque id felis. Morbi vel neque sit amet turpis dignissim egestas luctus eget nisl. Nullam vitae ante luctus, venenatis tellus vel, laoreet nisi. Integer et ornare felis. Sed in justo eget neque congue porta. Phasellus eget sagittis nibh, in rutrum erat.\n\nSed aliquet maximus est, vel aliquam lectus varius vitae. Duis posuere mollis tortor, ut lacinia arcu convallis quis. Quisque venenatis magna turpis, et interdum nisl blandit accumsan. Nullam eros orci, pharetra accumsan felis at, consectetur ullamcorper tellus. Morbi at scelerisque augue, sit amet viverra lorem. Maecenas tellus nulla, malesuada sit amet massa maximus, consequat venenatis felis. Sed sapien turpis, pharetra vel viverra sit amet, dictum ac est. Donec elementum, ipsum at iaculis maximus, est nibh tincidunt metus, a porta dolor velit ac lectus. Maecenas eget enim tempor metus semper iaculis ac eu arcu. Proin accumsan arcu non ipsum rhoncus semper. Integer eros urna, placerat vel ultricies vitae, sagittis at erat. Duis dapibus erat a convallis pharetra. Aenean orci est, placerat in ultrices ut, sodales eget arcu. Donec eu ipsum diam. Donec ultricies, orci id iaculis tempus, magna eros gravida ante, eget eleifend turpis ex ut libero. Quisque rutrum mollis tortor, interdum bibendum eros laoreet vel.\n\nNam sit amet gravida neque. Curabitur suscipit imperdiet efficitur. Nam eu turpis a lacus luctus mattis. Cras est dolor, euismod rutrum ultricies ut, rutrum a augue. Sed at mauris dolor. Nunc a arcu viverra, tempor ipsum et, mollis lorem. Nunc consequat dolor justo. Maecenas placerat nisi id urna egestas, vitae lacinia urna consequat. Sed eget mauris dui. Cras efficitur, odio et porttitor mattis, urna purus porta massa, eu ornare mauris lectus quis ligula. Phasellus a justo facilisis, scelerisque urna sit amet, pulvinar dolor.\n\nDuis tincidunt velit velit. Duis a leo eget nunc tincidunt luctus sit amet id risus. Nullam ullamcorper velit elit, nec luctus augue lacinia eu. Mauris fringilla ullamcorper elit, vitae sollicitudin ipsum tincidunt at. Curabitur eu magna ut velit hendrerit euismod vitae vitae nulla. Maecenas congue turpis vel ullamcorper commodo. Integer dolor ante, feugiat sed rutrum et, dapibus porttitor ex.";
